// blindtyper-react/src/App.tsx
import { useState, useEffect, useRef, useCallback } from "react";
import { InfoHeader } from "./components/InfoHeader";
import { Quote } from "./components/Quote";
import { currentTime, getDurationInMinutes } from "./utils/time";
import "./App.css";

const DEFAULT_ACCURACY = 100;
const API_URL = "https://baconipsum.com/api/?type=meat-and-filler&paras=1";

function App() {
  const [quote, setQuote] = useState("");
  const [wpm, setWpm] = useState(0);
  const [cpm, setCpm] = useState(0);
  const [accuracy, setAccuracy] = useState(DEFAULT_ACCURACY);
  const [isLoading, setLoading] = useState(true);
  const [text, setText] = useState("");
  const [wordCount, setWordCount] = useState(0);
  const [currentChar, setCurrentChar] = useState("");
  const [startTime, setStartTime] = useState(0);
  const [outgoingChars, setOutgoingChars] = useState("");
  const [isCorrectChar, setCorrectChar] = useState(true);
  const [errorChars, setErrorChars] = useState(0);
  const [fetchError, setFetchError] = useState("");
  const intervalId = useRef<number>();

  const initQuoteStates = useCallback((quote: string) => {
    /*     
      We need this because API is strange and places two spaces
      after the end of the sentence. 
    */
    const newQuote = quote.replace(/\s{2}/g, " ");
    setQuote(newQuote);
    setCurrentChar(newQuote.charAt(0));
    setText(newQuote.substring(1));
  }, []);

  const getQuoteData = useCallback(async () => {
    try {
      const response = await fetch(API_URL);
      const [data] = await response.json();
      initQuoteStates(data);
      setLoading(false);
    } catch (error) {
      setFetchError(`An error fetching quote. ${error}`);
    }
  }, [initQuoteStates]);

  useEffect(() => {
    getQuoteData();
  }, [getQuoteData]);

  useEffect(() => {
    intervalId.current = setInterval(updateCpmAndWpm, 200);

    return () => {
      clearInterval(intervalId.current);
    };
  });

  const calculateWpm = useCallback((wordCount: number, durationInMinutes: number) => {
    return Math.round(wordCount / durationInMinutes);
  }, []);

  const calculateCpm = useCallback((charCount: number, durationInMinutes: number) => {
    return Math.round(charCount / durationInMinutes);
  }, []);

  const calculateAccuracy = useCallback((errorChars: number, originalText: string) => {
    return Math.max((1000 - Math.round((1000 * errorChars) / originalText.length)) / 10, 0);
  }, []);

  const initStartTime = useCallback(() => {
    if (!startTime) {
      setStartTime(currentTime());
    }
  }, [startTime]);

  const isFinished = () => {
    const finished = outgoingChars.length === quote.length;

    if (finished) {
      clearInterval(intervalId.current);
    }

    return finished;
  };

  const updateCpmAndWpm = useCallback(() => {
    if (startTime) {
      const durationInMinutes = getDurationInMinutes(startTime);
      const newCpm = calculateCpm(outgoingChars.length, durationInMinutes);
      const newWpm = calculateWpm(wordCount, durationInMinutes);
      setCpm(newCpm);
      setWpm(newWpm);
    }
  }, [calculateCpm, calculateWpm, outgoingChars.length, startTime, wordCount]);

  const reset = useCallback(() => {
    setLoading(true);
    getQuoteData();
    setWpm(0);
    setCpm(0);
    setAccuracy(DEFAULT_ACCURACY);
    setText("");
    setWordCount(0);
    setCurrentChar("");
    setStartTime(0);
    setOutgoingChars("");
    setCorrectChar(true);
    setErrorChars(0);
  }, [getQuoteData]);

  // Return the focus on our hidden input if we lost it
  const handleBlur = useCallback(({ target }: React.FocusEvent<HTMLInputElement, Element>) => {
    target.focus();
  }, []);

  // Hack for FireFox to disable a Tab key
  useEffect(() => {
    function disableTabKey(this: Window, event: KeyboardEvent) {
      const { key } = event;
      if (key === "Tab") {
        event.preventDefault();
      }
    }

    window.addEventListener("keydown", disableTabKey);

    return () => {
      window.removeEventListener("keydown", disableTabKey);
    };
  });

  const handleErrorChar = useCallback(() => {
    if (!isCorrectChar) return; // exit if last try was already incorrect

    const newError = errorChars + 1;
    const newAccuracy = calculateAccuracy(newError, quote);

    setCorrectChar(false);
    setAccuracy(newAccuracy);
    setErrorChars(newError);
  }, [calculateAccuracy, errorChars, isCorrectChar, quote]);

  const handleNewChar = useCallback(
    (durationInMinutes: number) => {
      let updatedOutgoingChars = outgoingChars;
      updatedOutgoingChars += currentChar;
      setOutgoingChars(updatedOutgoingChars);
      setCurrentChar(text.charAt(0));
      setText(text.substring(1));
      setCorrectChar(true);

      const newCpm = calculateCpm(updatedOutgoingChars.length, durationInMinutes);
      setCpm(newCpm);
    },
    [calculateCpm, currentChar, outgoingChars, text]
  );

  const handleNewWord = useCallback(
    (durationInMinutes: number) => {
      const newWordCount = wordCount + 1;
      const newWpm = calculateWpm(newWordCount, durationInMinutes);
      setWordCount(newWordCount);
      setWpm(newWpm);
    },
    [calculateWpm, wordCount]
  );

  const handleKeyDown = useCallback(
    ({ key }: React.KeyboardEvent<HTMLInputElement>) => {
      initStartTime();

      // Check only real characters, don't check e.g. "Tab", "Shift", etc.
      if (key.length === 1) {
        const durationInMinutes = getDurationInMinutes(startTime);

        if (key === currentChar) {
          handleNewChar(durationInMinutes);

          if (text.charAt(0) === " ") {
            handleNewWord(durationInMinutes);
          }
        } else {
          handleErrorChar();
        }
      }
    },
    [currentChar, handleErrorChar, handleNewChar, handleNewWord, initStartTime, startTime, text]
  );

  if (fetchError) {
    return <p>{fetchError}</p>;
  }

  if (isLoading) {
    return <p>Loading...</p>;
  }

  if (isFinished()) {
    return (
      <div>
        <p>You nailed it! Literally :D</p>
        <InfoHeader cpm={cpm} wpm={wpm} accuracy={accuracy} />
        <button onClick={reset}>Reset</button>
      </div>
    );
  }
  return (
    <div className="flex">
      <input
        type="text"
        name="hiddenType"
        id="hiddenType"
        autoFocus
        autoComplete="off"
        onKeyDown={handleKeyDown}
        onBlur={handleBlur}
      />
      <div className="quote-block">
        <Quote text={text} char={currentChar} outgoingChars={outgoingChars} isCorrectChar={isCorrectChar}></Quote>
        <button className="quote-block_button" onClick={reset}>
          Reset
        </button>
      </div>
      <InfoHeader cpm={cpm} wpm={wpm} accuracy={accuracy} />
    </div>
  );
}

export default App;

// blindtyper-vue/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import InfoHeader from './components/InfoHeader.vue'
import Quote from './components/Quote.vue'
import { currentTime, getDurationInMinutes } from './utils/time';
import { checkWorldRecord } from './utils/record';


const DEFAULT_ACCURACY = 100;
const API_URL = 'https://baconipsum.com/api/?type=meat-and-filler&paras=1';

const quote = ref('');
const wpm = ref(0);
const cpm = ref(0);
const accuracy = ref(DEFAULT_ACCURACY);
const isLoading = ref(true);
const text = ref('');
const wordCount = ref(0);
const currentChar = ref('');
const startTime = ref(0);
const outgoingChars = ref('');
const isCorrectChar = ref(true);
const errorChars = ref(0);
const fetchError = ref('');
const intervalId = ref<number>();

const initQuoteStates = (quoteText: string) => {
  const newQuote = quoteText.replace(/\s{2}/g, ' ');
  quote.value = newQuote;
  currentChar.value = newQuote.charAt(0);
  text.value = newQuote.substring(1);
};

const getQuoteData = async () => {
  try {
    const response = await fetch(API_URL);
    const [data] = await response.json();
    initQuoteStates(data);
    isLoading.value = false;
  } catch (error) {
    fetchError.value = `An error fetching quote. ${error}`;
  }
};

const calculateWpm = (wordCount: number, durationInMinutes: number) => {
  return Math.round(wordCount / durationInMinutes);
};

const calculateCpm = (charCount: number, durationInMinutes: number) => {
  return Math.round(charCount / durationInMinutes);
};

const calculateAccuracy = (errorChars: number, originalText: string) => {
  return Math.max((1000 - Math.round((1000 * errorChars) / originalText.length)) / 10, 0);
};

const initStartTime = () => {
  if (!startTime.value) {
    startTime.value = currentTime();
  }
};

const isFinished = () => {
  const finished = outgoingChars.value.length === quote.value.length;

  if (finished) {
    clearInterval(intervalId.value);
  }

  return finished;
};

const reset = () => {
  isLoading.value = true;
  getQuoteData();
  wpm.value = 0;
  cpm.value = 0;
  accuracy.value = DEFAULT_ACCURACY;
  text.value = '';
  wordCount.value = 0;
  currentChar.value = '';
  startTime.value = 0;
  outgoingChars.value = '';
  isCorrectChar.value = true;
  errorChars.value = 0;
}

const handleBlur = (event: Event) => {
  console.log("Return focus");
  (event.target as HTMLInputElement).focus();
};

const updateCpmAndWpm = () => {
  if (startTime.value) {
    const durationInMinutes = getDurationInMinutes(startTime.value);
    const newCpm = calculateCpm(outgoingChars.value.length, durationInMinutes);
    const newWpm = calculateWpm(wordCount.value, durationInMinutes);
    cpm.value = newCpm;
    wpm.value = newWpm;

  }
}

function disableTabKey(this: Window, event: KeyboardEvent) {
  const { key } = event;
  if (key === "Tab") {
    event.preventDefault();
  }
}

const handleErrorChar = () => {
  if (!isCorrectChar.value) return; // exit if last try was already incorrect

  const newError = errorChars.value + 1;
  const newAccuracy = calculateAccuracy(newError, quote.value);

  isCorrectChar.value = false;
  accuracy.value = newAccuracy;
  errorChars.value = newError;
}

const handleNewChar = (durationInMinutes: number) => {
  let updatedOutgoingChars = outgoingChars.value;
  updatedOutgoingChars += currentChar.value;
  outgoingChars.value = updatedOutgoingChars;
  currentChar.value = text.value.charAt(0)
  text.value = text.value.substring(1)
  isCorrectChar.value = true;

  const newCpm = calculateCpm(updatedOutgoingChars.length, durationInMinutes);
  cpm.value = (newCpm);
}

const handleNewWord = (durationInMinutes: number) => {
  const newWordCount = wordCount.value + 1;
  const newWpm = calculateWpm(newWordCount, durationInMinutes);
  wordCount.value = newWordCount;
  wpm.value = newWpm;
}

const handleKeyDown = (event: KeyboardEvent) => {
  const { key } = event;
  initStartTime();

  // Check only real characters, don't check e.g. "Tab", "Shift", etc.
  if (key.length === 1) {
    const durationInMinutes = getDurationInMinutes(startTime.value);
    if (key === currentChar.value) {
      handleNewChar(durationInMinutes);

      if (text.value.charAt(0) === " ") {
        handleNewWord(durationInMinutes);
      }
    } else {
      handleErrorChar();
    }
  }
}

onMounted(() => {
  window.addEventListener("keydown", disableTabKey);
  getQuoteData();
  intervalId.value = setInterval(updateCpmAndWpm, 200);
});

onUnmounted(() => {
  window.removeEventListener("keydown", disableTabKey);
  clearInterval(intervalId.value);
});

</script>

<template>
  <template v-if="fetchError">{{ fetchError }}</template>
  <template v-else-if="isLoading">Loading...</template>
  <template v-else-if="isFinished()">
    <p>{{ checkWorldRecord(cpm) }}</p>
    <InfoHeader :cpm="cpm" :wpm="wpm" :accuracy="accuracy" />
    <button @click="reset">Reset</button>
  </template>
  <template v-else>
    <div class="flex">
      <input name="hiddenType" id="hiddenType" autoFocus="true" autoComplete="off" @keydown="handleKeyDown"
        @blur="handleBlur" />
      <div class="quote-block">
        <Quote :text="text" :char="currentChar" :outgoingChars="outgoingChars" :isCorrectChar="isCorrectChar" />
        <button class="quote-block_button" @click="reset">Reset</button>
      </div>
      <InfoHeader :wpm="wpm" :cpm="cpm" :accuracy="accuracy" />
    </div>
  </template>
</template>

<style scoped>
#hiddenType {
  color: transparent;
  background-color: transparent;
  overflow: hidden;
  border: none;
  caret-color: transparent;
  outline: 0;
  height: 1px;
}

.flex {
  display: flex;
  justify-content: space-between;
}

.quote-block_button {
  display: inline-block;
  margin: 0 auto;
  margin-bottom: 2rem;
}

@media (max-width: 768px) {
  .flex {
    flex-direction: column;
  }
}
</style>
